services:
  app:
    build: .
    container_name: web-profile
    ports:
      - "3003:3000"
    environment:
      NEXT_PUBLIC_API_URL: https://api-prod.bankwonosobo.co.id/publication
      NEXT_PUBLIC_AUTH_API_URL: https://api-prod.bankwonosobo.co.id
    networks:
      - web-profile-network

networks:
  web-profile-network:
    external: true
