name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # from secret
          password: ${{ secrets.DOCKER_PASSWORD }} # from secret

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: bankwonosobo/nextjs-company-profile:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # deploy ke vps
      - name: Deploy ke vps
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          # /home/server-vps1/.ssh/ssh_private
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/server-vps1/deployments/web-profile
            sudo docker compose pull
            sudo docker compose up -d
